//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSales.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public int ID { get; set; }
        public string CustomerID { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string FeedBack1 { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
